[workspace]
members = ["crates/*"]
resolver = "2"
default-members = ["crates/build-rootfs"]

# [profile.release]
# panic = "unwind"

[profile.thin]
inherits = "release"
panic = "abort"
strip = true
lto = "thin"
# opt-level = "s"
