#!/bin/sh -x
# ----------
# depends:
#     - dash | ash
#     - gnutar (tar) | bsdtar (libarchive-tools)
# ----------
panic() {
    echo "[ERROR] $@" >&2
    exit 1
}

name="$1"

case "$name" in
    [![:space:]]*) ;;
    *) panic "The first arg ($name) must start with a non-space" ;;
esac

# Unmounts the container's (/proc, /sys, etc.) mount points before packing. And it always returns true.
umount --lazy --verbose --force "$name"/* || true

pack_to_tar() {
    # If the tar command exists, use tar, otherwise use bsdtar.
    case "$(command -v tar)" in
        *tar) tar=tar ;;
        *) tar=bsdtar ;;
    esac

    $tar --posix \
        --directory "$name" \
        "--exclude=proc/*" \
        "--exclude=sys/*" \
        "--exclude=tmp/*" \
        "--exclude=var/tmp/*" \
        "--exclude=run/*" \
        "--exclude=mnt/*" \
        "--exclude=media/*" \
        "--exclude=var/cache/apt/pkgcache.bin" \
        "--exclude=var/cache/apt/srcpkgcache.bin" \
        "--exclude=var/cache/apt/archives/*deb" \
        "--exclude=var/cache/apt/archives/partial/*" \
        "--exclude=var/cache/archive-copier/*" \
        "--exclude=var/lib/apt/lists/*.*" \
        "--exclude=dev/*" \
        "--exclude=boot/*" \
        "--exclude=root/.*_history" \
        --create \
        --file /mnt/"$name".tar \
        .
}

pack_to_tar && {
    # When the path is "/", "//+", ".", ".+", "./", ".//+",
    # it will exit directly to avoid accidental deletion.
    awk -v DIR="$name" 'BEGIN {
        # if (DIR ~ /^(\/)$|^\/(\/)+$|^\.+$|^(\.\/)$|^(\.\/)(\/)+$/)
        if (DIR ~ /^(\.\/|\/)(\/)*$|^\.+$/) exit(1)
    }' && rm -rf "$name"
}
