#!/bin/zsh -fex

# git checkout dev
if [[ $PWD =~ -ci$ ]] {
    cd ../debian-museum
}

env CARGO_TARGET_DIR=/tmp/musl cross build --package get-ctr --profile no-lto --target=x86_64-unknown-linux-musl -v

cp /tmp/musl/x86_64-unknown-linux-musl/no-lto/get-ctr ./tmp.get-ctr

docker build -t reg.tmoe.me:2096/rs/get-ctr:x64 .

docker push reg.tmoe.me:2096/rs/get-ctr:x64
