[[mirror]]
name = "Official"
global = true
url = "https://archive.debian.org/debian/dists/"

[[mirror]]
region = "CN"
name = "NJU"
global = false
url = "https://mirrors.nju.edu.cn/debian-archive/debian/dists/"

# Bo
[[os]]
codename = "Bo"
version = "1.3"
date = "1997-10"
# title = "1.3 Bo (1997-10)"
path = "bo/main/"
base_tgz = "base1_3.tgz"

[[os.disk]]
arch = "x86"
# deb-arch = "i386"
path = "disks-i386/1997-10-13/"
date = "1997-10-13"


# Hamm
[[os]]
codename = "Hamm"
version = "2.0"
date = "1998-07"
# title = "2.0 Hamm (1998-07)"
path = "hamm/main/"
base_tgz = "base2_0.tgz"

[[os.disk]]
arch = "x86"
path = "disks-i386/2.0.10_1998-07-21/"
date = "1998-07-21"

[[os.disk]]
arch = "m68k"
path = "disks-m68k/1998-07-23/common/"
date = "1998-07-23"


# Slink
[[os]]
codename = "Slink"
version = "2.1"
date = "1999-03"
# title = "2.1 Slink (1999-03)"
path = "slink/main/"
base_tgz = "base2_1.tgz"
# arch = ["alpha", "x86", "m68k", "sparc"]

[[os.disk]]
arch = "alpha"
path = "disks-alpha/1999-03-05/"
date = "1999-03-05"

[[os.disk]]
arch = "x86"
path = "disks-i386/2.1.12-1999-12-09/"
date = "1999-12-09"

[[os.disk]]
arch = "m68k"
path = "disks-m68k/2.1.9.2-2000-03-02/common/"
date = "2000-03-02"

[[os.disk]]
arch = "sparc"
path = "disks-sparc/2.1.8.1-1999-03-01/"
date = "1999-03-01"


# Potato
[[os]]
codename = "Potato"
version = "2.2"
date = "2000-12"
path = "potato/main/"
base_tgz = "base2_2.tgz"
# arch = ["alpha", "armel", "ppc", "x86", "m68k", "sparc"]

[[os.disk]]
arch = "alpha"
path = "disks-alpha/2.2.20-2000-12-03/"
date = "2000-12-03"

[[os.disk]]
arch = "armel"
path = "disks-arm/current/"
date = "2001-06-08"

[[os.disk]]
arch = "ppc"
path = "disks-powerpc/current/"
date = "2001-04-15"

[[os.disk]]
arch = "x86"
path = "disks-i386/2.2.26-2001-06-14/"
date = "2001-06-14"

[[os.disk]]
arch = "m68k"
path = "disks-m68k/2.2.19-2000-12-03/"
date = "2001-12-03"

[[os.disk]]
arch = "sparc"
path = "disks-sparc/2.2.22-2001-04-13/"
date = "2001-04-13"
