# Bo
[[os]]
codename = "Bo"
version = "1.3"
date = "1997-10"
# title = "1.3 Bo (1997-10)"
path = "dists/bo/main/"
base_tgz = "base1_3.tgz"

[[os.disk]]
arch = "x86"
deb_arch = "i386"
path = "disks-i386/1997-10-13/"
date = "1997-10-13"
# mirror = "debian-archive"
# file_name = "1.3_Bo_x86_base_1997-10-13.tar.zst"
# "os.version_os.codename_disk.arch_disk.tag_disk.date".tar.zst
# "1.3_Bo_x86__1997-10-13.tar.zst"

# Hamm
[[os]]
codename = "Hamm"
version = "2.0"
date = "1998-07"
# title = "2.0 Hamm (1998-07)"
path = "dists/hamm/main/"
base_tgz = "base2_0.tgz"

[[os.disk]]
arch = "x86"
# deb_arch = "i386"
path = "disks-i386/2.0.10_1998-07-21/"
date = "1998-07-21"
# mirror = "debian-archive"

[[os.disk]]
arch = "m68k"
path = "disks-m68k/1998-07-23/common/"
date = "1998-07-23"
# mirror = "debian-archive"

# Slink
[[os]]
codename = "Slink"
version = "2.1"
date = "1999-03"
# title = "2.1 Slink (1999-03)"
path = "dists/slink/main/"
base_tgz = "base2_1.tgz"

[os.patch]
add-src-mirrors = true

[[os.disk]]
arch = "alpha"
path = "disks-alpha/1999-03-05/"
date = "1999-03-05"
# mirror = "debian-archive"

[[os.disk]]
arch = "x86"
deb_arch = "i386"
path = "disks-i386/2.1.12-1999-12-09/"
date = "1999-12-09"
# mirror = "debian-archive"

[[os.disk]]
arch = "m68k"
path = "disks-m68k/2.1.9.2-2000-03-02/common/"
date = "2000-03-02"
# mirror = "debian-archive"

[[os.disk]]
arch = "sparc"
path = "disks-sparc/2.1.8.1-1999-03-01/"
date = "1999-03-01"
# mirror = "debian-archive"


# Potato
[[os]]
codename = "Potato"
version = "2.2"
date = "2000-12"
path = "dists/potato/main/"
base_tgz = "base2_2.tgz"
# arch = ["alpha", "armv3", "ppc", "x86", "m68k", "sparc"]

[os.patch]
add-src-mirrors = true

[[os.disk]]
arch = "alpha"
path = "disks-alpha/2.2.20-2000-12-03/"
date = "2000-12-03"
tag = "base"
# mirror = "debian-archive"

[[os.disk]]
arch = "armv3"
deb_arch = "arm"
path = "disks-arm/current/"
date = "2001-06-08"
tag = "base"
# mirror = "debian-archive"

[[os.disk]]
arch = "ppc"
deb_arch = "powerpc"
path = "disks-powerpc/current/"
date = "2001-04-15"
tag = "base"
# mirror = "debian-archive"

[[os.disk]]
arch = "x86"
deb_arch = "i386"
path = "disks-i386/2.2.26-2001-06-14/"
date = "2001-06-14"
tag = "base"
# mirror = "debian-archive"

[[os.disk]]
arch = "m68k"
path = "disks-m68k/2.2.19-2000-12-03/"
date = "2001-12-03"
tag = "base"
# mirror = "debian-archive"

[[os.disk]]
arch = "sparc"
path = "disks-sparc/2.2.22-2001-04-13/"
date = "2001-04-13"
tag = "base"
# mirror = "debian-archive"
