#!/usr/bin/zsh -fx

deb_components=(
    main
    contrib
    non-free
    # non-free-firmware
)

uuu_components=(
    main
    restricted
    universe
    multiverse
)

variant=$1

# zsh anonymous function
() {
    local IFS=','
    case $variant {
        ("deb") 
            IFS=' '
            print $deb_components 
        ;;

        # The "$arr" must be in double quotes
        ("deb-debootstrap")  print "${deb_components}" ;;

        ("uuu")
            IFS=' '
            print $uuu_components
        ;;

        ("uuu-debootstrap") print "${uuu_components}" ;;

        (*)
    <<HELP
    Available values:
        - deb
        - deb-debootstrap
        - uuu
        - uuu-debootstrap
    Example:
        get-deb-components uuu
HELP
    ;;
    }
}
