#!/bin/sh -x
case $1 in
    "-h" | "--help" | "")
    cat<<-'HELP_INFO'
    Example:

    ```zsh
    container_dir="debian-woody-i386"
    pkgs_arr=(
        nano
        wget
        ca-certificates
    )

    # It will install the packages in the pkgs_arr in order (i.e., nano first, then wget ...).
    install-pkgs-in-container $container_dir $pkgs_arr
    ```
HELP_INFO
exit 0
;;
esac

dir=$1
shift
systemd-nspawn -D "$dir" -E LANG=C sh -c "
    for i in $*; do
        apt-get install --assume-yes --force-yes \$i
    done
    "
