#!/usr/bin/env zsh
# depends: curl, tomlyre
#
set -fexo pipefail
url='https://raw.githubusercontent.com/2moe/circle-runner/main/.circleci/config.yml'
cfg=circle/arm64.yml
large=circle/large.yml
common_key="jobs.setup-runner"
curl -Lo $cfg $url

tomlyre set $cfg -k ${common_key}.environment.REPO -s "2cd" --save

cp $cfg $large

tomlyre set $large -k ${common_key}.resource_class -s "arm.large" --save

for f ($cfg $large) {
    sed '1i # This file is automatically generated, do not edit it manually.' -i $f
}
