#!/usr/bin/env zsh
# depends: curl, tomlyre
#
set -fexo pipefail
url='https://raw.githubusercontent.com/2moe/circle-runner/main/.circleci/config.yml'
cfg=circle/arm64.yml
curl -Lo $cfg $url
tomlyre set $cfg -k jobs.setup-runner.environment.REPO -s "2cd" --save

sed '1i # This file is automatically generated, do not edit it manually.' -i $cfg
