name: build pkg (get-ctr)
# 0.0.0-alpha.2
# auto-task.start-build-time = ?

on:
  schedue:
    - cron: '0 11 28 */2 *'
  push:
    branches: ["dev"]
    paths:
      - .github/workflows/cross.rs.yml
      - assets/cross/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: zsh --pipefail -fex {0}
    env:
      PROFILE: no-lto
      CARGO_TARGET_DIR: /tmp/rs
      DOCKER_DIR: assets/cross
    steps:
      - name: install zsh
        shell: sh -e {0}
        run: ${{ vars.INSTALL_ZSH }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          # ref: main
          repository: 'cross-rs/cross'

      - name: check rustc
        run:

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ${{env.CARGO_TARGET_DIR}}
          key: ${{ runner.os }}-cargo-cross

      - uses: dtolnay/rust-toolchain@stable
      - name: cargo build
        run: |
          cargo build --package get-ctr --profile ${{env.PROFILE}}
          cargo -Vv

      - uses: actions/checkout@v4
        with:
          ref: build

      - name: copy bin to docker context
        env:
          tmp: ${{env.DOCKER_DIR}}/tmp
          bin_dir: ${{env.CARGO_TARGET_DIR}}/${{env.PROFILE}}
        run: |
          mkdir -pv $tmp
          cp -vf $bin_dir/cross* $tmp

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{env.DOCKER_DIR}}/tmp
          file: ${{env.DOCKER_DIR}}/Dockerfile
          push: true
          tags: ghcr.io/2cd/pkgs:cross-x64
