name: build pkg (get-ctr)
# 0.0.0-alpha.2
# auto-task.start-build-time = ?
# on: { "push": { "branch": dev, "paths": [".github/workflows/rs.yml", "Cargo.toml"] } }

on:
  push:
    branches: ["dev"]
    paths:
      - .github/workflows/get-ctr.rs.yml
      - assets/build-get-ctr/Dockerfile
      - Cargo.toml
      - Cargo.lock
      - 'crates/get-ctr/src/**/*'
      - crates/get-ctr/Cargo.toml

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      PROFILE: no-lto
      CARGO_TARGET_DIR: /tmp/rs
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          ref: dev

      - uses: actions/cache@v3
        if: runner.arch == 'X64'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ${{env.CARGO_TARGET_DIR}}
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@stable
      - name: cargo build
        run: |
          cargo build --package get-ctr --profile ${{env.PROFILE}}
          type cargo rustc rustup ||:

      - uses: actions/checkout@v4
        with:
          ref: build

      - name: copy bin to docker context
        run: install -Dm755 ${{env.CARGO_TARGET_DIR}}/${{env.PROFILE}}/get-ctr assets/build-get-ctr/tmp.get-ctr

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: assets/build-get-ctr
          push: true
          tags: ghcr.io/2cd/pkgs:get-ctr-x64
