name: get Bo, Hamm, Slink & Potato rootfs

env:
  DEBIAN_FRONTEND: noninteractive

on:
  push:
    # branches:
    #   - master
    paths:
      - ".github/workflows/old-old-debian.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: zsh -f -e {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: install zsh
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

      - name: get-base-disk.bin
        run: docker run -it --rm -v /usr/local/bin:/host reg.tmoe.me:2096/rs/get-base-disk:x64 cp get-base-disk /host

      - name: download rootfs
        run: get-base-disk -h
