name: build zsh-builder
# 0.0.0-alpha.2
# auto-task.start-build-time = ?
# on: { "push": { "branch": dev, "paths": [".github/workflows/rs.yml", "Cargo.toml"] } }

on:
  push:
    branches: ["dev", "build"]
    paths: [".github/workflows/rs.yml", "Cargo.toml"]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      PROFILE: no-lto
      CARGO_TARGET_DIR: /tmp/rs
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          ref: dev
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo build
        run: cargo build --package get-ctr --profile ${{env.PROFILE}}

      - uses: actions/checkout@v4
        with:
          ref: build

      - name: install get-ctr
        run: install -Dm755 ${{env.CARGO_TARGET_DIR}}/${{env.PROFILE}}/get-ctr assets/build-get-ctr/tmp.get-ctr

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: assets/build-get-ctr
          push: true
          tags: ghcr.io/2cd/pkg/get-ctr:x64
